[tox]
env_list = cov, py311, py312, py313, py314
isolated_build = true
skip_missing_interpreters = true

[testenv]
deps =
    pytest>=8
    pytest-asyncio
    pytest-cov>=5
    python-jose[cryptography]
    cryptography
    httpx
    pico-boot
    pico-ioc[yaml]
    pico-fastapi
    pico-client-auth
commands = pytest {posargs:tests}

[testenv:cov]
commands = pytest --cov=pico_server_auth --cov-report=term-missing tests
